name: Tailscale Server
on:
  workflow_dispatch: {}
   

jobs:
  run-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tailscale + jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Enable IP Forwarding
        run: |
          sudo sysctl -w net.ipv4.ip_forward=1
          sudo sysctl -w net.ipv6.conf.all.forwarding=1


      - name: Start Tailscale Exit Node
        run: |
          sudo tailscale up \
            --authkey ${{ secrets.TAILSCALE_AUTHKEY }} \
            --ssh \
            --advertise-exit-node \
            --hostname=git-server \
            --reset
        env:
          TS_SOCKET: /tmp/tailscaled.sock

      - name: Save Start Time
        run: |
          START_TIME=$(date +%s)
          echo "START_TIME=$START_TIME" >> $GITHUB_ENV


      - name: Cleanup Exit Node
        if: always()
        run: |
          sudo tailscale down

